version: '3.8'

services:
  app: 
    build: .  # Constroi a imagem a partir do Dockerfile na raiz do projeto
    container_name: my_app_container  # Nome do container
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do host para a porta 8000 do container
    volumes:
      - .:/app
